import product1 from "@/assets/product-1.jpg";
import product2 from "@/assets/product-2.jpg";
import product3 from "@/assets/product-3.jpg";
import product4 from "@/assets/product-4.jpg";
import product5 from "@/assets/product-5.jpg";
import product6 from "@/assets/product-6.jpg";

// Cremes
import c1 from "@/assets/cremes/c1.webp";
import c2 from "@/assets/cremes/c2.avif";
import c3 from "@/assets/cremes/c3.webp";

// Hoodies
import h1 from "@/assets/hoodies/h1.webp";
import h2 from "@/assets/hoodies/h2.jpg";
import h3 from "@/assets/hoodies/h3.jpeg";
import h4 from "@/assets/hoodies/h4.webp";
import h5 from "@/assets/hoodies/h5.webp";

// Joggings
import j1 from "@/assets/joggings/j1.jpg";
import j2 from "@/assets/joggings/j2.jpeg";
import j3 from "@/assets/joggings/j3.jpg";
import j4 from "@/assets/joggings/j4.webp";
import j5 from "@/assets/joggings/j5.webp";
import j5_1 from "@/assets/joggings/j5-1.webp";
import j6 from "@/assets/joggings/j6.avif";

// Lunettes
import l1 from "@/assets/lunettes/l1.webp";
import l2 from "@/assets/lunettes/l2.webp";
import l3 from "@/assets/lunettes/l3.webp";
import l4 from "@/assets/lunettes/l4.webp";

// Robes
import r1 from "@/assets/robes/r1.jpg";
import r2 from "@/assets/robes/r2.jpg";
import r3 from "@/assets/robes/r3.jpg";
import r4 from "@/assets/robes/r4.jpg";
import r5 from "@/assets/robes/r5.jpeg";
import r6 from "@/assets/robes/r6.webp";
import r7 from "@/assets/robes/r7.jpg";
import r8 from "@/assets/robes/r8.webp";
import r9 from "@/assets/robes/r9.webp";
import r10 from "@/assets/robes/r10.webp";
import r11 from "@/assets/robes/r11.webp";

// Sacs
import s1 from "@/assets/sac_a_main/s1.webp";
import s2 from "@/assets/sac_a_main/s2.jpg";
import s3 from "@/assets/sac_a_main/s3.webp";
import s4 from "@/assets/sac_a_main/s4.webp";
import s5 from "@/assets/sac_a_main/s5.webp";
import s6 from "@/assets/sac_a_main/s6.webp";
import s7 from "@/assets/sac_a_main/s7.webp";
import s8 from "@/assets/sac_a_main/s8.png";
import s9 from "@/assets/sac_a_main/s9.webp";
import s10 from "@/assets/sac_a_main/s10.jpg";

// Sweats
import sw1 from "@/assets/sweats/sw1.jpg";
import sw2 from "@/assets/sweats/sw2.jpg";
import sw3 from "@/assets/sweats/sw3.jpg";

export type Product = {
  id: string;
  name: string;
  price: number;
  image: string;
  category: "mode" | "cosmetique";
  subcategory: string;
  badge?: "Nouveau" | "Bestseller";
  description: string;
  colors?: string[];
  sizes?: string[];
  brand: string;
  rating: number;
  reviews: number;
};

export const products: Product[] = [
  // Existing placeholder products
  {
    id: "pull-cashmere-creme",
    name: "Pull cachemire oversize",
    price: 189,
    image: product1,
    category: "mode",
    subcategory: "femme",
    badge: "Bestseller",
    brand: "Valorie",
    description:
      "Pull en cachemire pur, coupe oversize pour un confort absolu. Doux, chaud et intemporel.",
    colors: ["Crème", "Taupe", "Noir"],
    sizes: ["XS", "S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 124,
  },
  {
    id: "sac-cuir-nude",
    name: "Sac cabas en cuir",
    price: 295,
    image: product2,
    category: "mode",
    subcategory: "accessoires",
    badge: "Nouveau",
    brand: "Atelier Rive",
    description:
      "Sac cabas en cuir véritable, finitions soignées et format idéal pour le quotidien.",
    colors: ["Nude", "Cognac", "Noir"],
    rating: 4.9,
    reviews: 87,
  },
  {
    id: "serum-eclat",
    name: "Sérum éclat vitaminé",
    price: 68,
    image: product3,
    category: "cosmetique",
    subcategory: "visage",
    badge: "Bestseller",
    brand: "Botanique",
    description:
      "Un sérum concentré pour une peau lumineuse et repulpée dès la première application.",
    rating: 4.7,
    reviews: 312,
  },
  {
    id: "rouge-mat-nude",
    name: "Rouge à lèvres mat nude",
    price: 32,
    image: product4,
    category: "cosmetique",
    subcategory: "maquillage",
    badge: "Nouveau",
    brand: "Lude",
    description: "Une formule mate longue tenue, confortable, dans une teinte nude universelle.",
    colors: ["Nude rosé", "Beige", "Terracotta"],
    rating: 4.6,
    reviews: 96,
  },
  {
    id: "robe-soie-beige",
    name: "Robe en soie midi",
    price: 245,
    image: product5,
    category: "mode",
    subcategory: "femme",
    brand: "Valorie",
    description: "Robe midi en soie fluide, parfaite pour les soirées et événements raffinés.",
    colors: ["Beige", "Ivoire", "Sauge"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviews: 58,
  },
  {
    id: "creme-hydratante",
    name: "Crème hydratante nuit",
    price: 78,
    image: product6,
    category: "cosmetique",
    subcategory: "visage",
    badge: "Bestseller",
    brand: "Botanique",
    description: "Une crème nuit régénérante aux actifs naturels pour réveiller votre éclat.",
    rating: 4.8,
    reviews: 214,
  },

  // Cremes
  {
    id: "creme-hydra-intense-rose",
    name: "Crème Hydratante Intense Rose",
    price: 54,
    image: c1,
    category: "cosmetique",
    subcategory: "visage",
    brand: "Botanique",
    description: "Formule veloutée enrichie en extraits de rose pour nourrir et repulper intensément votre visage au quotidien.",
    colors: ["Blanche"],
    rating: 4.8,
    reviews: 43,
  },
  {
    id: "serum-anti-age-cellulaire",
    name: "Sérum Anti-Âge Cellulaire",
    price: 82,
    image: c2,
    category: "cosmetique",
    subcategory: "visage",
    badge: "Nouveau",
    brand: "Lude",
    description: "Un sérum de nuit concentré en actifs régénérants pour restaurer la fermeté et l'éclat naturel de votre peau.",
    rating: 4.7,
    reviews: 29,
  },
  {
    id: "baume-botanique-reparateur",
    name: "Baume Botanique Réparateur",
    price: 28,
    image: c3,
    category: "cosmetique",
    subcategory: "corps",
    brand: "Botanique",
    description: "Un baume onctueux multi-usages enrichi en beurre de karité pour apaiser les zones sèches et hydrater vos lèvres.",
    rating: 4.9,
    reviews: 74,
  },

  // Hoodies
  {
    id: "hoodie-oversize-coton-noir",
    name: "Hoodie Oversize Coton Noir",
    price: 95,
    image: h1,
    category: "mode",
    subcategory: "femme",
    brand: "Valorie",
    description: "Sweat-shirt à capuche décontracté à la coupe oversize minimaliste, parfait pour un style urbain élégant.",
    colors: ["Noir", "Charbon"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.6,
    reviews: 82,
  },
  {
    id: "sweat-capuche-creme-premium",
    name: "Sweat à Capuche Crème Premium",
    price: 110,
    image: h2,
    category: "mode",
    subcategory: "homme",
    brand: "Atelier Rive",
    description: "Conçu en coton lourd haut de gamme pour une tenue structurée et un confort exceptionnel au quotidien.",
    colors: ["Crème", "Sable"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.9,
    reviews: 110,
  },
  {
    id: "hoodie-essentiel-gris-mouchete",
    name: "Hoodie Essentiel Gris Moucheté",
    price: 85,
    image: h3,
    category: "mode",
    subcategory: "femme",
    brand: "Atelier Rive",
    description: "Le classique indispensable du vestiaire sportswear avec sa doublure molletonnée ultra-douce.",
    colors: ["Gris"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.5,
    reviews: 64,
  },
  {
    id: "hoodie-zippe-confort-taupe",
    name: "Hoodie Zippé Confort Taupe",
    price: 120,
    image: h4,
    category: "mode",
    subcategory: "homme",
    badge: "Nouveau",
    brand: "Valorie",
    description: "Gilet à capuche avec fermeture éclair métallique, taillé dans un coton épais couleur taupe très raffiné.",
    colors: ["Taupe"],
    sizes: ["M", "L", "XL"],
    rating: 4.7,
    reviews: 38,
  },
  {
    id: "hoodie-velours-vert-foret",
    name: "Hoodie Velours Vert Forêt",
    price: 135,
    image: h5,
    category: "mode",
    subcategory: "femme",
    brand: "Botanique",
    description: "Le sweat à capuche revisité dans un velours de coton côtelé luxueux et ultra-doux au toucher.",
    colors: ["Vert Forêt"],
    sizes: ["S", "M", "L"],
    rating: 4.8,
    reviews: 51,
  },

  // Joggings
  {
    id: "pantalon-jogging-sable",
    name: "Pantalon de Jogging Sable",
    price: 80,
    image: j1,
    category: "mode",
    subcategory: "femme",
    brand: "Valorie",
    description: "Un bas de jogging en coton molletonné doux avec bords-côtes pour une silhouette décontractée chic.",
    colors: ["Sable", "Beige"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.7,
    reviews: 95,
  },
  {
    id: "jogging-coupe-slim-charbon",
    name: "Jogging Coupe Slim Charbon",
    price: 90,
    image: j2,
    category: "mode",
    subcategory: "homme",
    brand: "Atelier Rive",
    description: "Coupe ajustée moderne et cordon de serrage contrasté pour un look athlétique épuré.",
    colors: ["Charbon", "Noir"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.6,
    reviews: 73,
  },
  {
    id: "jogging-ample-anthracite",
    name: "Jogging Ample Anthracite",
    price: 75,
    image: j3,
    category: "mode",
    subcategory: "femme",
    badge: "Nouveau",
    brand: "Valorie",
    description: "Coupe ample décontractée avec taille haute élastiquée pour un confort sans compromis.",
    colors: ["Anthracite"],
    sizes: ["S", "M", "L"],
    rating: 4.4,
    reviews: 42,
  },
  {
    id: "jogging-doux-blanc-casse",
    name: "Jogging Doux Blanc Cassé",
    price: 95,
    image: j4,
    category: "mode",
    subcategory: "femme",
    brand: "Atelier Rive",
    description: "La pureté du blanc cassé associée à une maille bouclette douillette haut de gamme.",
    colors: ["Blanc Cassé"],
    sizes: ["XS", "S", "M"],
    rating: 4.8,
    reviews: 55,
  },
  {
    id: "jogging-sport-bleu-marine",
    name: "Jogging Actif Bleu Marine",
    price: 85,
    image: j5,
    category: "mode",
    subcategory: "homme",
    brand: "Valorie",
    description: "Jogging de sport fonctionnel doté de poches zippées discrètes et d'une matière respirante.",
    colors: ["Bleu Marine"],
    sizes: ["M", "L", "XL"],
    rating: 4.7,
    reviews: 80,
  },
  {
    id: "pantalon-jogger-cargo-kaki",
    name: "Pantalon Jogger Cargo Kaki",
    price: 110,
    image: j5_1,
    category: "mode",
    subcategory: "homme",
    badge: "Bestseller",
    brand: "Atelier Rive",
    description: "Style d'inspiration militaire avec poches cargo latérales et bas de jambe resserrés élastiqués.",
    colors: ["Kaki"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 130,
  },
  {
    id: "jogging-fluide-rose-nude",
    name: "Jogging Fluide Rose Nude",
    price: 89,
    image: j6,
    category: "mode",
    subcategory: "femme",
    brand: "Valorie",
    description: "Un confort soyeux grâce à son tissage de modal écologique au tomber fluide élégant.",
    colors: ["Rose Nude"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviews: 67,
  },

  // Lunettes
  {
    id: "lunettes-soleil-ecaille",
    name: "Lunettes de Soleil Écaille",
    price: 145,
    image: l1,
    category: "mode",
    subcategory: "accessoires",
    badge: "Bestseller",
    brand: "Atelier Rive",
    description: "Monture rétro en acétate écaille de tortue et verres polarisés de catégorie 3.",
    colors: ["Marron", "Écaille"],
    rating: 4.8,
    reviews: 142,
  },
  {
    id: "lunettes-ovales-minimalistes-noir",
    name: "Lunettes Ovales Minimalistes Noir",
    price: 160,
    image: l2,
    category: "mode",
    subcategory: "accessoires",
    brand: "Valorie",
    description: "Monture fine ovale en acétate brillant noir, un clin d'œil intemporel aux années 90.",
    colors: ["Noir"],
    rating: 4.6,
    reviews: 58,
  },
  {
    id: "lunettes-aviateur-monture-or",
    name: "Lunettes Aviateur Monture Or",
    price: 185,
    image: l3,
    category: "mode",
    subcategory: "accessoires",
    badge: "Nouveau",
    brand: "Atelier Rive",
    description: "Finesse métallique dorée et double pont emblématique pour un style aviateur affirmé.",
    colors: ["Or"],
    rating: 4.7,
    reviews: 31,
  },
  {
    id: "lunettes-carrees-cristal-rose",
    name: "Lunettes Carrées Cristal Rose",
    price: 150,
    image: l4,
    category: "mode",
    subcategory: "accessoires",
    brand: "Valorie",
    description: "Sublimez vos tenues avec cette monture translucide rose cristal et ses verres teintés dégradés.",
    colors: ["Rose"],
    rating: 4.5,
    reviews: 49,
  },

  // Robes
  {
    id: "robe-cache-coeur-fleurie",
    name: "Robe Cache-Cœur Fleurie",
    price: 185,
    image: r1,
    category: "mode",
    subcategory: "femme",
    badge: "Bestseller",
    brand: "Valorie",
    description: "Robe portefeuille en viscose fluide à imprimé fleuri délicat pour un look romantique chic.",
    colors: ["Rouge", "Imprimé"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.8,
    reviews: 104,
  },
  {
    id: "robe-longue-de-soiree-noire",
    name: "Robe Longue de Soirée Noire",
    price: 290,
    image: r2,
    category: "mode",
    subcategory: "femme",
    brand: "Valorie",
    description: "Silhouette fluide drapée et dos nu sophistiqué, l'alliée idéale de vos soirées d'exception.",
    colors: ["Noir"],
    sizes: ["S", "M", "L"],
    rating: 4.9,
    reviews: 36,
  },
  {
    id: "robe-chemise-en-lin-blanc",
    name: "Robe Chemise en Lin Blanc",
    price: 135,
    image: r3,
    category: "mode",
    subcategory: "femme",
    brand: "Atelier Rive",
    description: "Confectionnée en lin lavé léger et thermorégulateur, boutonnée sur toute la longueur.",
    colors: ["Blanc"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 82,
  },
  {
    id: "robe-midi-plissee-emeraude",
    name: "Robe Midi Plissée Émeraude",
    price: 210,
    image: r4,
    category: "mode",
    subcategory: "femme",
    brand: "Valorie",
    description: "Tissu plissé élégant couleur émeraude avec ceinture assortie pour marquer joliment la taille.",
    colors: ["Vert"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.8,
    reviews: 57,
  },
  {
    id: "robe-pull-en-laine-merinos",
    name: "Robe Pull en Laine Mérinos",
    price: 175,
    image: r5,
    category: "mode",
    subcategory: "femme",
    badge: "Nouveau",
    brand: "Valorie",
    description: "Une robe pull tricotée dans une laine mérinos fine et chaude avec un col roulé élégant.",
    colors: ["Gris"],
    sizes: ["S", "M", "L"],
    rating: 4.6,
    reviews: 29,
  },
  {
    id: "robe-d-ete-bretelles-nouees",
    name: "Robe d'Été Bretelles Nouées",
    price: 120,
    image: r6,
    category: "mode",
    subcategory: "femme",
    brand: "Atelier Rive",
    description: "Coupe évasée fraîche dotée de bretelles ajustables à nouer sur l'épaule.",
    colors: ["Jaune"],
    sizes: ["XS", "S", "M"],
    rating: 4.5,
    reviews: 44,
  },
  {
    id: "robe-portefeuille-satin-nude",
    name: "Robe Portefeuille Satin Nude",
    price: 230,
    image: r7,
    category: "mode",
    subcategory: "femme",
    brand: "Valorie",
    description: "Satin de soie délicat couleur champagne au drapé flatteur et ultra-féminin.",
    colors: ["Nude"],
    sizes: ["S", "M", "L"],
    rating: 4.8,
    reviews: 73,
  },
  {
    id: "robe-boheme-dentelle-ivoire",
    name: "Robe Bohème Dentelle Ivoire",
    price: 260,
    image: r8,
    category: "mode",
    subcategory: "femme",
    brand: "Atelier Rive",
    description: "Style bohème poétique rehaussé de guipures et dentelles sur une doublure douce en coton.",
    colors: ["Ivoire"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviews: 52,
  },
  {
    id: "robe-trapeze-denim-leger",
    name: "Robe Trapèze Denim Léger",
    price: 145,
    image: r9,
    category: "mode",
    subcategory: "femme",
    brand: "Atelier Rive",
    description: "Toile de coton effet denim souple et poches plaquées pour une allure décontractée structurée.",
    colors: ["Bleu Denim"],
    sizes: ["S", "M", "L"],
    rating: 4.6,
    reviews: 69,
  },
  {
    id: "robe-asymetrique-volants",
    name: "Robe Asymétrique Volants",
    price: 195,
    image: r10,
    category: "mode",
    subcategory: "femme",
    badge: "Nouveau",
    brand: "Valorie",
    description: "Épaule asymétrique et volants légers pour une allure dansante résolument chic.",
    colors: ["Rouge"],
    sizes: ["S", "M"],
    rating: 4.7,
    reviews: 18,
  },
  {
    id: "robe-en-maille-ajouree-creme",
    name: "Robe en Maille Ajourée Crème",
    price: 180,
    image: r11,
    category: "mode",
    subcategory: "femme",
    brand: "Valorie",
    description: "Robe longue en maille fine ajourée, parfaite sur un maillot de bain ou doublée pour les soirées.",
    colors: ["Crème"],
    sizes: ["S", "M", "L"],
    rating: 4.8,
    reviews: 35,
  },

  // Sacs
  {
    id: "sac-porte-epaule-cuir-noir",
    name: "Sac Porté Épaule Cuir Noir",
    price: 320,
    image: s1,
    category: "mode",
    subcategory: "accessoires",
    badge: "Bestseller",
    brand: "Atelier Rive",
    description: "Le sac baguette parfait en cuir grainé noir doté d'une fermeture dorée sécurisée.",
    colors: ["Noir"],
    rating: 4.9,
    reviews: 156,
  },
  {
    id: "sac-seau-cuir-velours-camel",
    name: "Sac Seau Cuir Velours Camel",
    price: 280,
    image: s2,
    category: "mode",
    subcategory: "accessoires",
    brand: "Atelier Rive",
    description: "Format généreux en cuir suédé avec cordon de serrage et bandoulière amovible.",
    colors: ["Camel", "Marron"],
    rating: 4.8,
    reviews: 94,
  },
  {
    id: "pochette-de-soiree-satin-noir",
    name: "Pochette de Soirée Satin Noir",
    price: 140,
    image: s3,
    category: "mode",
    subcategory: "accessoires",
    brand: "Valorie",
    description: "Design enveloppe épuré en satin noir avec fine bandoulière chaîne amovible dorée.",
    colors: ["Noir"],
    rating: 4.7,
    reviews: 42,
  },
  {
    id: "mini-sac-bandouliere-creme",
    name: "Mini Sac Bandoulière Crème",
    price: 195,
    image: s4,
    category: "mode",
    subcategory: "accessoires",
    badge: "Nouveau",
    brand: "Atelier Rive",
    description: "Format mini rigide très élégant en cuir lisse écru pour sublimer vos looks.",
    colors: ["Crème", "Blanc"],
    rating: 4.8,
    reviews: 27,
  },
  {
    id: "grand-cabas-raphia-cuir",
    name: "Grand Cabas Raphia & Cuir",
    price: 210,
    image: s5,
    category: "mode",
    subcategory: "accessoires",
    brand: "Atelier Rive",
    description: "Raphia naturel tressé à la main orné d'anses et de finitions en cuir marron végétal.",
    colors: ["Naturel"],
    rating: 4.9,
    reviews: 83,
  },
  {
    id: "sac-baguette-effet-croco",
    name: "Sac Baguette Effet Croco",
    price: 240,
    image: s6,
    category: "mode",
    subcategory: "accessoires",
    brand: "Valorie",
    description: "Embossage croco bordeaux verni pour une touche rétro sophistiquée ultra-tendance.",
    colors: ["Bordeaux"],
    rating: 4.6,
    reviews: 61,
  },
  {
    id: "tote-bag-grand-format-lin",
    name: "Tote Bag Grand Format Lin",
    price: 95,
    image: s7,
    category: "mode",
    subcategory: "accessoires",
    brand: "Atelier Rive",
    description: "Toile de lin enduite ultra-résistante avec de larges anses, idéale pour le week-end.",
    colors: ["Naturel"],
    rating: 4.5,
    reviews: 39,
  },
  {
    id: "sac-portefeuille-cuir-nude",
    name: "Sac Portefeuille Cuir Nude",
    price: 165,
    image: s8,
    category: "mode",
    subcategory: "accessoires",
    brand: "Valorie",
    description: "Compagnon compact 2-en-1 en cuir souple avec emplacements cartes et bandoulière amovible.",
    colors: ["Nude"],
    rating: 4.7,
    reviews: 53,
  },
  {
    id: "sac-besace-vintage-marron",
    name: "Sac Besace Vintage Marron",
    price: 260,
    image: s9,
    category: "mode",
    subcategory: "accessoires",
    badge: "Bestseller",
    brand: "Atelier Rive",
    description: "Cuir marron patiné au style vintage intemporel doté d'une fermeture cartable classique.",
    colors: ["Marron"],
    rating: 4.9,
    reviews: 114,
  },
  {
    id: "sac-messenger-toile-cuir",
    name: "Sac Messenger Toile & Cuir",
    price: 220,
    image: s10,
    category: "mode",
    subcategory: "accessoires",
    brand: "Atelier Rive",
    description: "Toile épaisse imperméable kaki rehaussée de lanières en cuir de sellerie marron.",
    colors: ["Kaki", "Marron"],
    rating: 4.6,
    reviews: 48,
  },

  // Sweats
  {
    id: "sweat-col-rond-bleu-marine",
    name: "Sweat Col Rond Bleu Marine",
    price: 75,
    image: sw1,
    category: "mode",
    subcategory: "homme",
    brand: "Atelier Rive",
    description: "Sweat col rond en coton bio ultra doux, l'incontournable décontracté par excellence.",
    colors: ["Bleu Marine"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.7,
    reviews: 89,
  },
  {
    id: "sweat-brode-maison-eden",
    name: "Sweat Brodé Valorie",
    price: 95,
    image: sw2,
    category: "mode",
    subcategory: "femme",
    badge: "Bestseller",
    brand: "Valorie",
    description: "Broderie fine signature sur la poitrine pour ce sweat en coton écru premium.",
    colors: ["Ecru"],
    sizes: ["XS", "S", "M", "L"],
    rating: 4.9,
    reviews: 120,
  },
  {
    id: "sweat-col-montant-demi-zip",
    name: "Sweat Col Montant Demi-Zip",
    price: 110,
    image: sw3,
    category: "mode",
    subcategory: "homme",
    badge: "Nouveau",
    brand: "Valorie",
    description: "Molleton lourd, col montant demi-zippé et cordon de resserrage en bas de vêtement.",
    colors: ["Gris"],
    sizes: ["S", "M", "L", "XL"],
    rating: 4.8,
    reviews: 33,
  },
];

export const getProduct = (id: string) => products.find((p) => p.id === id);
export const getByCategory = (cat: "mode" | "cosmetique") =>
  products.filter((p) => p.category === cat);
