/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RechercheRouteImport } from './routes/recherche'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as ModeRouteImport } from './routes/mode'
import { Route as FemmeRouteImport } from './routes/femme'
import { Route as FavorisRouteImport } from './routes/favoris'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CosmetiqueRouteImport } from './routes/cosmetique'
import { Route as AProposRouteImport } from './routes/a-propos'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProduitIdRouteImport } from './routes/produit.$id'
import { Route as FemmeSacsRouteImport } from './routes/femme.sacs'

const RechercheRoute = RechercheRouteImport.update({
  id: '/recherche',
  path: '/recherche',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const ModeRoute = ModeRouteImport.update({
  id: '/mode',
  path: '/mode',
  getParentRoute: () => rootRouteImport,
} as any)
const FemmeRoute = FemmeRouteImport.update({
  id: '/femme',
  path: '/femme',
  getParentRoute: () => rootRouteImport,
} as any)
const FavorisRoute = FavorisRouteImport.update({
  id: '/favoris',
  path: '/favoris',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CosmetiqueRoute = CosmetiqueRouteImport.update({
  id: '/cosmetique',
  path: '/cosmetique',
  getParentRoute: () => rootRouteImport,
} as any)
const AProposRoute = AProposRouteImport.update({
  id: '/a-propos',
  path: '/a-propos',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProduitIdRoute = ProduitIdRouteImport.update({
  id: '/produit/$id',
  path: '/produit/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FemmeSacsRoute = FemmeSacsRouteImport.update({
  id: '/sacs',
  path: '/sacs',
  getParentRoute: () => FemmeRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cosmetique': typeof CosmetiqueRoute
  '/dashboard': typeof DashboardRoute
  '/favoris': typeof FavorisRoute
  '/femme': typeof FemmeRouteWithChildren
  '/mode': typeof ModeRoute
  '/panier': typeof PanierRoute
  '/recherche': typeof RechercheRoute
  '/femme/sacs': typeof FemmeSacsRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cosmetique': typeof CosmetiqueRoute
  '/dashboard': typeof DashboardRoute
  '/favoris': typeof FavorisRoute
  '/femme': typeof FemmeRouteWithChildren
  '/mode': typeof ModeRoute
  '/panier': typeof PanierRoute
  '/recherche': typeof RechercheRoute
  '/femme/sacs': typeof FemmeSacsRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/a-propos': typeof AProposRoute
  '/cosmetique': typeof CosmetiqueRoute
  '/dashboard': typeof DashboardRoute
  '/favoris': typeof FavorisRoute
  '/femme': typeof FemmeRouteWithChildren
  '/mode': typeof ModeRoute
  '/panier': typeof PanierRoute
  '/recherche': typeof RechercheRoute
  '/femme/sacs': typeof FemmeSacsRoute
  '/produit/$id': typeof ProduitIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/a-propos'
    | '/cosmetique'
    | '/dashboard'
    | '/favoris'
    | '/femme'
    | '/mode'
    | '/panier'
    | '/recherche'
    | '/femme/sacs'
    | '/produit/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/a-propos'
    | '/cosmetique'
    | '/dashboard'
    | '/favoris'
    | '/femme'
    | '/mode'
    | '/panier'
    | '/recherche'
    | '/femme/sacs'
    | '/produit/$id'
  id:
    | '__root__'
    | '/'
    | '/a-propos'
    | '/cosmetique'
    | '/dashboard'
    | '/favoris'
    | '/femme'
    | '/mode'
    | '/panier'
    | '/recherche'
    | '/femme/sacs'
    | '/produit/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AProposRoute: typeof AProposRoute
  CosmetiqueRoute: typeof CosmetiqueRoute
  DashboardRoute: typeof DashboardRoute
  FavorisRoute: typeof FavorisRoute
  FemmeRoute: typeof FemmeRouteWithChildren
  ModeRoute: typeof ModeRoute
  PanierRoute: typeof PanierRoute
  RechercheRoute: typeof RechercheRoute
  ProduitIdRoute: typeof ProduitIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/recherche': {
      id: '/recherche'
      path: '/recherche'
      fullPath: '/recherche'
      preLoaderRoute: typeof RechercheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mode': {
      id: '/mode'
      path: '/mode'
      fullPath: '/mode'
      preLoaderRoute: typeof ModeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/femme': {
      id: '/femme'
      path: '/femme'
      fullPath: '/femme'
      preLoaderRoute: typeof FemmeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favoris': {
      id: '/favoris'
      path: '/favoris'
      fullPath: '/favoris'
      preLoaderRoute: typeof FavorisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cosmetique': {
      id: '/cosmetique'
      path: '/cosmetique'
      fullPath: '/cosmetique'
      preLoaderRoute: typeof CosmetiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/a-propos': {
      id: '/a-propos'
      path: '/a-propos'
      fullPath: '/a-propos'
      preLoaderRoute: typeof AProposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produit/$id': {
      id: '/produit/$id'
      path: '/produit/$id'
      fullPath: '/produit/$id'
      preLoaderRoute: typeof ProduitIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/femme/sacs': {
      id: '/femme/sacs'
      path: '/sacs'
      fullPath: '/femme/sacs'
      preLoaderRoute: typeof FemmeSacsRouteImport
      parentRoute: typeof FemmeRoute
    }
  }
}

interface FemmeRouteChildren {
  FemmeSacsRoute: typeof FemmeSacsRoute
}

const FemmeRouteChildren: FemmeRouteChildren = {
  FemmeSacsRoute: FemmeSacsRoute,
}

const FemmeRouteWithChildren = FemmeRoute._addFileChildren(FemmeRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AProposRoute: AProposRoute,
  CosmetiqueRoute: CosmetiqueRoute,
  DashboardRoute: DashboardRoute,
  FavorisRoute: FavorisRoute,
  FemmeRoute: FemmeRouteWithChildren,
  ModeRoute: ModeRoute,
  PanierRoute: PanierRoute,
  RechercheRoute: RechercheRoute,
  ProduitIdRoute: ProduitIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
